title: Awesome-competitive-programming
description: ":gem: A curated list of awesome Competitive Programming, Algorithm and Data Structure resources"
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
